apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${SERVICE_NAME}-${ENVIRONMENT}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containerConcurrency: 80
      containers:
        - image: ${CONTAINER_IMAGE}
  traffic:
    - percent: 100
      latestRevision: true